### 첫번째 머신러닝 만들어 보기 - 붓꽃 품종 예측하기

In [2]:
#붓꽃 데이터를 불러오기
from sklearn.datasets import load_iris

In [3]:
#모듈을 기반으로 학습 (클래스 적용 후 의사결정 나무를 사용할 수 있도록)
from sklearn.tree import DecisionTreeClassifier

In [4]:
#데이터 세트를 학습 데이터와 테스트 데이터로 분리 하는데 train_test_split 함수 (4절과 관련)
from sklearn.model_selection import train_test_split

In [5]:
import pandas as pd

#iris data 불러오기 (Iris 데이터 세트에서 feature 만으로 된 데이터를 numpy.ndarray로 갖고 있음)
iris = load_iris()
iris_data= iris.data

print(type(iris_data))
print(iris_data)

<class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3

In [6]:
#iris target 불러오기
iris_label=iris.target
print('iris target 값:\n' ,iris_label)
print('iris target 명:\n' ,iris.target_names)
print(type(iris.target))

iris target 값:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명:
 ['setosa' 'versicolor' 'virginica']
<class 'numpy.ndarray'>


In [9]:
#붓꽃 데이터 세트를 데이터 프레임으로 변환
iris_df = pd.DataFrame(data=iris_data, columns= iris.feature_names)


#label이라는 새 컬럼을 만든다.
iris_df['label']=iris.target
iris_df.head()



sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [ ]:
#학습용 데이터와 테스트 용 데이터 분리 (n%가 테스트 데이터)
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [ ]:
# 객체 생성이란? DecisionTreeClassifier라는 설계도(클래스)로 dt_clf라는 도구(객체)를 만드는 것과 같음

dt_clf=DecisionTreeClassifier(random_state=11)


In [ ]:
#fit : 모델을 학습시키는 함수
#학습수행

dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [ ]:
#학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
#예측은 학습 데이터가 아닌 것으로 실행 

pred = dt_clf.predict(X_test)

In [ ]:
#예측 결과를 기반으로 예측 성능 평가(정확도 측정)
from sklearn.metrics import accuracy_score
print('예측정확도 : {0:.4f}'.format(accuracy_score(y_test,pred)))

예측정확도 : 0.9333


### 사이킷 런 기반의 프레임워크 익히기

#클래스 : 속성과 기능을 가진 설계도

Estimator 

- Classifier 클래스
- Regressor 클래스


#모듈 : 함수/변수/클래스 등을 모아놓은 파일로 필요할 때마다 가져 쓸 수 있는 도구 상자
#모듈에서 클래스를 import(꺼내서 사용한다.)
#모듈 종류 pg.92-93

In [ ]:
#의사결정 트리 알고리즘을 제공하는 모듈에서 클래스 import
from sklearn.tree (모듈) import DecisionTreeClassifier (클래스)

#클래스로 객체 만들기 
dt_clf (객체)=DecisionTreeClassifier(random_state=11) (클래스)

#객체를 함수로 운용하기
dt_clf.fit(X_train, y_train)


#API : Application Programming Interface
애플리케이션이 서로 상호작용할 수 있도록 하는 도구 집합

#내장된 데이터 세트 (Pg. 94)
분류/회귀 용도로 사용하고 실습할 수 있는 데이터

#표본 데이터 생성기 (Pg. 95)
데이터 세트를 무작위로 생성하는 도구 중 하나


In [ ]:
#사이킷 런에 내장된 데이터 세트 알아보기
#데이터는 Bunch 로 나타난다.
from sklearn.datasets import load_iris
iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


In [ ]:
#Bunch 객체 안에 있는 것이 'key'
#컬럼 이름은 feature_names 안에 들어 있는 것

keys=iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)

#Pg.96  데이터 구조 도표 참고

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
print('\n feature_names 의 type:',type(iris_data.feature_names))
print(' feature_names 의 shape:',len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names 의 type:',type(iris_data.target_names))
print(' feature_names 의 shape:',len(iris_data.target_names))
print(iris_data.target_names)

print('\n data 의 type:',type(iris_data.data))
print(' data 의 shape:',iris_data.data.shape)
print(iris_data['data'])

print('\n target 의 type:',type(iris_data.target))
print(' target 의 shape:',iris_data.target.shape)
print(iris_data.target)



 feature_names 의 type: <class 'list'>
 feature_names 의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names 의 type: <class 'numpy.ndarray'>
 feature_names 의 shape: 3
['setosa' 'versicolor' 'virginica']

 data 의 type: <class 'numpy.ndarray'>
 data 의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0